### PR TITLE
fix for mac, reduce ticks per beat

### PR DESCRIPTION
**Pull request by GermanAizek**
@lupiter, is your fix ready for PR?
Thank you for taking the time to develop the old Heath's project. It is a pity that the author cannot be contacted in any way.

### CODE REVIEW

**Review by Lexa307 — APPROVED** [review]
Well done dude. Thank you for your care.

**Review by GermanAizek — COMMENTED** [review]
Thank you for your activity, waiting for the @lupiter response

**Comment by lupiter** [comment]
I wouldn't recommend merging this as-is, I just hacked on it until it ran and produced something that looked kind of right. I might have broken running this on Windows. When I'm feeling better I'll try and tidy this fix up so it can be merged.

**Comment by lupiter** [comment]
This should be nicer for everyone 😄 

Changes in this PR:

1. Use `fopen_s` only on Windows (where it exists) and use good old `fopen` otherwise.
2. Optionally allow another argument to specify the output file name, in case you'd like something other than "test.mod"
3. Read an environment variable to (optionally) override the fallback ticks per beat. If your midi file doesn't specify a tempo, but you'd like something other than 64 ticks per beat (quite slow) then set `TICKS_PER_BEAT` e.g. `TICKS_PER_BEAT=4; ./midi2mod my_cool_song.midi`
4. Add a .gitignore file to ignore the build artefacts, plus any MIDI or MOD files you accidentally leave in your working directory.

**Comment by GermanAizek** [comment]
@lupiter, good job my friend.
Now the tool has a more flexible setup, I merge your commits.
Thank you so much for your activity.

**Pull request merged**
